# General settings
base_output_dir: "dataset"
log_level: "INFO"

# Screenshot settings
screenshot_freq: 10

# Audio settings
audio_channels: 1
audio_samplerate: 44100

# Data saving settings
buffer_size: 100
buffer_time: 5  # seconds

# Mouse and keyboard settings
mouse_move_throttle: 0.05  # seconds

# Privacy settings
mask_keys: ["Key.enter"]  # List of keys to mask in the log
